### PR TITLE
Chore/initial documentation edit

### PR DESCRIPTION
**Pull request by rhyslbw**
cc @darko-mijic

### CODE REVIEW

**Comment by darko-mijic** [comment]
Nicely distilled Rhys, brilliant job. There is just one thing i would revisit, I used Tracker-aware reactive data sources for "Meteor reactive data". Key thing about this library is leveraging Minimongo as Tracker-aware reactive data source. Let's ship this after your review @DominikGuzei.

**Comment by rhyslbw** [comment]
> Key thing about this library is leveraging Minimongo as Tracker-aware reactive data source.

How so? Could also be using a ReactiveVar or ReactiveDict right? I feel 'Meteor reactive data' is a more understood term than 'Tracker-aware data', which currently have the exact same meaning.

I will do another edit of the Before and After section though, as this is the real meat of the docs and should help someone evaluating the library to see the difference with the other approaches to implementing a non-blaze view layer.

**Comment by darko-mijic** [comment]
> How so? Could also be using a ReactiveVar or ReactiveDict right? I feel 'Meteor reactive data' is a more understood term than 'Tracker-aware data', which currently have the exact same meaning.

Yes, ReactiveVar and ReactiveDict could be used too since they are Tracker-aware. 'Meteor reactive data' sounds too generic to me. 

Here is Tracker documentation, there is section called "Tracker-aware libraries":
https://github.com/meteor/meteor/tree/devel/packages/tracker

**Comment by darko-mijic** [comment]
I will take over this PR for a while and update it with things we learned from applying this package to projection rebuilding example.

**Comment by DominikGuzei** [comment]
@darko-mijic can we merge this and you update the readme later on the way? There are many people waiting for this package and i would like to provide them with links.

**Comment by darko-mijic** [comment]
I have updated readme with usage example with MobX running in strict mode @DominikGuzei.

**Pull request merged**
